export const GET_FUNDS = 'GET_FUNDS';
export const GET_FUNDS_PENDING = 'GET_FUNDS_PENDING';
export const GET_FUNDS_FULFILLED = 'GET_FUNDS_FULFILLED';
export const GET_FUNDS_REJECTED = 'GET_FUNDS_REJECTED';

export const GET_FUND = 'GET_FUND';
export const GET_FUND_PENDING = 'GET_FUND_PENDING';
export const GET_FUND_FULFILLED = 'GET_FUND_FULFILLED';
export const GET_FUND_REJECTED = 'GET_FUND_REJECTED';

export const UPDATE_FUND = 'UPDATE_FUND';
export const UPDATE_FUND_PENDING = 'UPDATE_FUND_PENDING';
export const UPDATE_FUND_FULFILLED = 'UPDATE_FUND_FULFILLED';
export const UPDATE_FUND_REJECTED = 'UPDATE_FUND_REJECTED';
